//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detail
    {
        public int Id { get; set; }
        public string PatientDeasis { get; set; }
        public string BloodTest { get; set; }
        public string UrinTest { get; set; }
        public string OtherTest1 { get; set; }
        public string OtherTest2 { get; set; }
        public string OtherTest3 { get; set; }
        public string PatientRoomNumber { get; set; }
        public string AppointedDoctor { get; set; }
        public System.DateTime AdmitDate { get; set; }
    }
}
