//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor_Info
    {
        public int Id { get; set; }
        public string Doctor_Name { get; set; }
        public string Speacalist { get; set; }
        public string Duty_time { get; set; }
        public string Phone_Number { get; set; }
        public string Salary { get; set; }
    }
}
